# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', null=True, unique=True)),
                ('caption', models.TextField(blank=True, help_text='An optional summary.', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(help_text="Kindly optimize the image <a href='http://optimizilla.com/'>here</a> before uploading", upload_to='photos')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
