# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadidea',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='uploadidea',
            name='idea',
        ),
        migrations.AddField(
            model_name='uploadidea',
            name='bio',
            field=models.TextField(default='About You', max_length=3000),
        ),
        migrations.AddField(
            model_name='uploadidea',
            name='content',
            field=models.TextField(default='Your Idea', max_length=3000),
        ),
        migrations.AddField(
            model_name='uploadidea',
            name='title',
            field=models.CharField(default='Title', max_length=800),
        ),
        migrations.AlterField(
            model_name='uploadidea',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadidea',
            name='upload_image',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
